### ISSUE TITLE
Questions about how to generate infos_offline.

### ISSUE THREAD

**Issue by ZecCheng** [HYjhkoh/MGTANet#12]
Thanks for your great work about multi-frame point clouds 3D object detection. Could you please provide the code about how to generate infos_offline:infos_train_10sweeps_withvelo_filter_True_offline_3.pkl. It will help me a lot. Thank you very much~

**Comment by junhyung-SPALab** [comment]
Hello. I'm Junhyung lee, the co-author of this work. Thank you for your interest in our work.
We utilized the json data officially provided by the nuScenes dataset to construct multi-frame data for the online and offline mode models. Please refer to the [nuScenes data schema](https://www.nuscenes.org/nuscenes#data-format).

To be more specific, the json data is structured so that a unique token is assigned to each single frame, and each token is linked to each other for the same scene. Therefore, we utilized the json data and created a pickle file in the desired multi-frame configuration. Both online and offline modes are the same in that they are prepared using a given data structure.
I think the multi-frame pickle file generation code is currently not included in the MGTANet repository.
The code for **creating multi-frame pickle files** is uploaded to the repository for [D-Align](https://github.com/junhyung-SPALab/D-Align/blob/main/create_sequence_pickle.py), so it might be a good idea to refer to it.

Any additional questions are welcome !!

**Comment by ZecCheng** [comment]
> Hello. I'm Junhyung lee, the co-author of this work. Thank you for your interest in our work. We utilized the json data officially provided by the nuScenes dataset to construct multi-frame data for the online and offline mode models. Please refer to the [nuScenes data schema](https://www.nuscenes.org/nuscenes#data-format).
> 
> To be more specific, the json data is structured so that a unique token is assigned to each single frame, and each token is linked to each other for the same scene. Therefore, we utilized the json data and created a pickle file in the desired multi-frame configuration. Both online and offline modes are the same in that they are prepared using a given data structure. I think the multi-frame pickle file generation code is currently not included in the MGTANet repository. The code for **creating multi-frame pickle files** is uploaded to the repository for [D-Align](https://github.com/junhyung-SPALab/D-Align/blob/main/create_sequence_pickle.py), so it might be a good idea to refer to it.
> 
> Any additional questions are welcome !!

Thanks for your sincere reply! I have seen "The code for creating multi-frame pickle files is uploaded to the repository for [D-Align](https://github.com/junhyung-SPALab/D-Align/blob/main/create_sequence_pickle.py)", however, it may be different to generate pickle files in MGTANet. As for the infos_train_10sweeps_withvelo_filter_True_offline_3.pkl differs from nuscenes_seq_3_infos_10sweeps_train.pkl in D-Align due to the different structure you used in these two different frameworks. The former is based on det3d and the latter on OpenPCDet. Well, I wonder if you can upload your creating multi-frame pickle files in MGTANet, as it's important for me to do some ablation works. Thanks again for your great work and kind help! 😄
